name: Generate ADR TOC
on: [push, pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    name: genadr_readme
    steps:
      - uses: jules2689/adr-actions@main
        with:
          adr-dir: '' # Optional. Directory in which ADRs are located. Defaults to contents of .adr-dir
          adr-tool-repo: 'https://github.com/npryce/adr-tools.git' # Not Optional. ADR Tool Repo location
          adr-tool-version: '3.0.0' # Optional. Version of the Tools to use.
          github_token: '' # Optional. Token with which to commit
