name: My WF
on: push
jobs:
  my-first-job:
    name: "Hello, World."
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: super linter
#        uses: github/super-linter@v3
#        env:
#          DEFAULT_BRANCH: main
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test commandes
        run: echo 'Helllllllllloo' && pwd
