name: "vars"

on: push

env:
  #  ORGANISATION_NAME: friends-of-presta
  ORGANISATION_NAME: SebSept

jobs:
  ps_release:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Setup zipname. Exports $MODULE_NAME, $VERSION & $ZIP_FILE"
        uses: SebSept/module-release-action@early_dev
