name: "ps_release"

on:
  push:
    tags:
      - "*"

jobs:
  ps_release:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Setup zipname. Exports $MODULE_NAME, $VERSION & $ZIP_FILE"
        run: |
          MODULE_NAME=${GITHUB_REPOSITORY#*/}
          echo "MODULE_NAME=${MODULE_NAME}" >> $GITHUB_ENV
          REF='${{ github.ref }}'
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          VERSION=${REF#refs/*/}
          echo "ZIP_FILE=${MODULE_NAME}_${VERSION}.zip" >> $GITHUB_ENV
          echo zip : $ZIP_FILE
          echo version : $VERSION
          echo module : $MODULE_NAME
