name: "vars"

on: push

env:
  ORGANISATION_NAME: friends-of-presta
#  MODULE_NAME2: ${{ github.actor }}
#  MODULE_NAME3: ${{ {github.repository#github.repository_owner/} }}

jobs:
  ps_release:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Setup $MODULE_NAME"
        run: echo "MODULE_NAME=${GITHUB_REPOSITORY#$ORGANISATION_NAME/}" >> $GITHUB_ENV

      - name: "Echos"
        run: |
          echo gh : ${{ github.ref }}
          echo ZIP_NAME : ${ZIP_NAME}
        env:
          ZIP_NAME: ${{env.MODULE_NAME}}_${{ github.ref }}.zip
