name: "vars"

on:
  push:
    tags: '*'
    branches: "essais_divers"

jobs:
  ps_release:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Setup zipname. Exports $MODULE_NAME, $VERSION & $ZIP_FILE"
        uses: SebSept/module-release-action@early_dev
